### ISSUE TITLE
Location of the wwise script to launch authoring app

### ISSUE THREAD

**Issue by Nomys** [ferdiu/wwiser-launcher#1]
Hi,
Just probable some chair-computer interface problem, but went I launch the 'install_wwise.sh' inside the offline installer folder I have a question saying : 'Where do you want to install "wwise_2021.1.10.7883" script to launch authoring app?'. I answer to get it installed in my home. and I get this error: 

```
"/home/**********"/wwise_2021.1.10.7883: No file or folder found
cat: ./wwise_authoring_script: No file or folder found
chmod: impossible to access to '"/home/*********"/wwise_2021.1.10.7883': No file or folder found
```

I'm on Debian 11.

**Comment by ferdiu** [comment]
Hi,

sorry this project is still a WIP but should work for installing the Authoring app at this point: lately I haven't find much time to work on it.
That being said: the proper way to install the Authoring app is by launching the `wwiser-launcher.py` script (note the `py` extension) and then following the menu (`zenity` is required at this point, sorry):

**Comment by Nomys** [comment]
thanks for your reply!

Ok so the problem was I didn't launch the .py installer but the .sh inside the "installer" directory. I think the readme instructions are wrong about that.

Installation went well, I have now a bunch of missing dlls (from visual studio I guess ?) when I launch the Wwise.exe in /Audiokinetic/bla/bla/bin/

I'll check this later and get back to you :)

**Comment by ferdiu** [comment]
Hi, I'm really glad this helped you.

It would be really helpful (for future readers) if you can list the missing dynamic linked libraries (dll) you needed to manually install to make it work. Furthermore, as I mentioned, I do not really have time in this period to work on this project so I can't spend any time fixing (properly) the documentation for now but I would accept a PR if anyone would be so kind to make one _wink wink_. :D

PS did you used the Unity patch too? If yes, did it work right away?

**Comment by Nomys** [comment]
I don't know If I'll have the time myself, but i'll try.

The dll was mfc140u.dll (64bits) it was missing from /Windows/System.

I didn't try the Unity patch but in a month or so I will! I'll create a separate issue thread if i'll run into one.
